# Appendix B: Non-uniqueness of mean-field projection and of the DMET fixed point

# 1.Non-uniqueness of the mean-field projection

We show explicit non-uniqueness of the approximate projection by constructing two non-interacting system that have the same impurity 1RDM $\gamma^{s}_{\rm imp}(i,j)$ but different orbitals and thus projections. 

We first make a random choice for a non-interacting system. Let us consider a translation invariant Hubbard system , i.e., we have only next-neighbor hopping with periodic boundary conditions:
 \begin{align}
    \boldsymbol{h}^{s}=\begin{pmatrix}
0& -1    &  0 & 0& 0 &-1\\
-1& 0   &  -1 & 0& 0 &0\\
0& -1   &  0 & -1 & 0 &0\\
0& 0   &  -1 & 0 & -1 &0\\
0& 0   &  0 & -1 & 0 &-1\\
-1& 0   &  0 & 0 & -1 &0\\
\end{pmatrix}
\label{eq:ham_targ_6}
\end{align}

In [1]:
import numpy as np
from numpy import linalg as LA
from numpy.linalg import multi_dot
np.set_printoptions(precision=5)
import copy


h = -np.ones((6,6))
h *= np.tri(*h.shape, k=1)
np.fill_diagonal(h,0)
h *= 1 - np.tri(*h.shape, k=-2)
h[0,5]=-1
h[5,0]=-1

In [2]:
print(h)

[[ 0. -1. -0. -0. -0. -1.]
 [-1.  0. -1. -0. -0. -0.]
 [-0. -1.  0. -1. -0. -0.]
 [-0. -0. -1.  0. -1. -0.]
 [-0. -0. -0. -1.  0. -1.]
 [-1. -0. -0. -0. -1.  0.]]


Diagonalizing it leads to six eigenstates $\{\phi_{1}, ..., \phi_{6}\}$, and choosing the three lowest eigenstates $\{\phi_{1},\phi_{2},\phi_{3}\}$ with ground-state energy $E=-4$. 

In [3]:
epsilon, phi = LA.eigh(h)

In [4]:
E=epsilon[0]+epsilon[1]+epsilon[2]
print(E)

-3.9999999999999982


The 1RDM of  $\{\phi_{1},\phi_{2}, \phi_{3}\}$ reads:

 \begin{align}
    \boldsymbol{\gamma}^{s}=\begin{pmatrix}
0.5& 0.33333    &  0 & -0.16666& 0 &0.33333\\
0.33333& 0.5   &  0.33333 & 0& -0.16666 &0\\
0& 0.33333   &  0.5 & 0.33333 & 0 &-0.16666\\
-0.16666& 0   &  0.33333 & 0.5 & 0.33333 &0\\
0& -0.166666  &  0 & 0.33333& 0.5 &0.333333\\
0.333333& 0   &  -0.166666 & 0 & 0.333333 &0.5\\
\end{pmatrix}
\end{align}.

In [5]:
gamma_s=np.dot(phi[:,0:3],phi[:,0:3].transpose())
print(gamma_s)

[[ 5.00000e-01  3.33333e-01  1.60448e-16 -1.66667e-01  1.47285e-16
   3.33333e-01]
 [ 3.33333e-01  5.00000e-01  3.33333e-01 -2.30550e-17 -1.66667e-01
   8.26456e-17]
 [ 1.60448e-16  3.33333e-01  5.00000e-01  3.33333e-01  6.40920e-17
  -1.66667e-01]
 [-1.66667e-01 -2.30550e-17  3.33333e-01  5.00000e-01  3.33333e-01
  -2.12794e-17]
 [ 1.47285e-16 -1.66667e-01  6.40920e-17  3.33333e-01  5.00000e-01
   3.33333e-01]
 [ 3.33333e-01  8.26456e-17 -1.66667e-01 -2.12794e-17  3.33333e-01
   5.00000e-01]]


The resulting impurity 1RDM on $A \equiv\{1,2 \}$ is then
\begin{align}
    \boldsymbol{\gamma}^{s}_{\rm imp}=\begin{pmatrix}
0.5& 0.33333    \\
0.33333& 0.5    \\
\end{pmatrix}
\label{eq:gamma_t_imp}
\end{align}

In [6]:
gamma_imp=gamma_s[0:2,0:2]
print(gamma_imp)

[[0.5     0.33333]
 [0.33333 0.5    ]]


To then construct a different system with the same impurity 1RDM as its three-particle ground-state we first 
diagonalize $\boldsymbol{\gamma}_{\rm imp}$ and get the eigenvalues and the eigenvectors of the impurity 1RDM as
\begin{align}
n_1^{\rm imp}&=0.16666 \equiv \| \tilde{\varphi}_1\|_A^2\nonumber\\
\varphi^{A}_1 &=  0.70711 |1\rangle
 -0.70711  |2\rangle.
\end{align}
\begin{align}
n_2^{\rm imp}&=0.83333 \equiv \|\tilde{\varphi}_2\|_A^2 \nonumber\\
\varphi^{A}_2&= 0.70711 |1\rangle
 +0.70711  |2\rangle
  \label{eq:imp_occ_2}
\end{align}  

In [8]:
n_imp, phi_imp=LA.eigh(gamma_imp)
for i in range (0,2):
    print(n_imp[i])
    print(phi_imp[:,i])

0.1666666666666666
[ 0.70711 -0.70711]
0.833333333333333
[-0.70711 -0.70711]


Since $B$ is four-dimensional we have four basis functions. We can choose problem adopted ones by just diagonalizing the environment 1RDM of the original $\gamma^{s}(i,j)$ and use two of them to build our CAS space, i.e.

In [10]:
gamma_env=gamma_s[2:6,2:6]
print(gamma_env)

[[ 5.00000e-01  3.33333e-01  6.40920e-17 -1.66667e-01]
 [ 3.33333e-01  5.00000e-01  3.33333e-01 -2.12794e-17]
 [ 6.40920e-17  3.33333e-01  5.00000e-01  3.33333e-01]
 [-1.66667e-01 -2.12794e-17  3.33333e-01  5.00000e-01]]


This leads to
  \begin{align}
n_1&=0\equiv \|\tilde{\varphi}_1\|_B^2\\
\varphi^{B}_1&= - 0.31623|3\rangle+0.63246|4\rangle -0.63246|5\rangle +0.31623|6\rangle 
  \label{eq:env_unocc}
\end{align}

  \begin{align}
n_2&=  0.16666 \equiv \|\tilde{\varphi}_2\|_B^2\\   
\varphi^{B}_2&=
  0.63246 |3\rangle     
 -0.31623 |4\rangle
 -0.31623 |5 \rangle   
  +0.63246 |6\rangle \nonumber
  \label{eq:n_2_env}
  \end{align}
   \begin{align}
  n_3&= 0.83333 \equiv \|\tilde{\varphi}_3\|_B^2 \\
  \varphi^{B}_3&=
 -0.63246|3\rangle    
 -0.31623 |4\rangle+
  0.31623 |5\rangle+     
  0.63246 |6\rangle   
  \label{eq:n_3_env}
  \end{align}
 \begin{align}
 \label{eq:phi_core}
 n_4&= 1.0 \equiv \| \tilde{\varphi}_4\|_B^2\nonumber\\
 \varphi^{B}_4&=
  0.31623|3\rangle     + 0.63246  |4\rangle
+ 0.63246   |5\rangle+ 0.31623 |6\rangle.  
  \end{align}

In [11]:
n_env, phi_env = LA.eigh(gamma_env)
for i in range (0,4):
    print(n_env[i])
    print(phi_env[:,i])

-1.8219613577756638e-16
[-0.31623  0.63246 -0.63246  0.31623]
0.16666666666666677
[ 0.63246 -0.31623 -0.31623  0.63246]
0.8333333333333327
[ 0.63246  0.31623 -0.31623 -0.63246]
0.9999999999999998
[-0.31623 -0.63246 -0.63246 -0.31623]


We can construct the CAS orbitals that would be used in the auxiliary projection of the target Hamiltonian (where for the purpose of the example is not interacting but in a real application one would be interested in interacting Hamiltonians). The first two CAS orbitals can be always chosen as

\begin{align}
    \varphi^{\rm CAS}_1&= |1\rangle, 
  \label{eq:phi_1_cas}
  \\
    \varphi^{\rm CAS}_2&= |2\rangle.
  \label{eq:phi_2_cas}
\end{align}

Alternatively, we could have used the two orbitals $\phi^A$ of the impurity submatrix as we have discussed in the previous Appendix. Because the fourth eigenvector of the environment submatrix is discarded in the usual approximate projection (unentangled occupied/core orbital) and the first orbital is perpendicular to the subspace of the three lowest orbitals, we build the other CAS (environmental) orbitals from the remaining orbitals as
\begin{align}
    \varphi^{\rm CAS}_3&=\varphi^{B}_2,
  \label{eq:phi_3_cas}
\\
  \varphi^{\rm CAS}_4&=\varphi^{B}_3.
  \label{eq:phi_4_cas}
\end{align}
While we do not need this CAS orbitals in this section, they will become important in the next. Further, they will show that we get a very different projection when we compare to the CAS from the different Hamiltonian that we construct next.   

In [12]:
phi_CAS=np.zeros((6,4))
for i in range(2):
    phi_CAS[i,i]=1
    phi_CAS[2:6,i+2]=phi_env[:,i+1]
print(phi_CAS)    

[[ 1.       0.       0.       0.     ]
 [ 0.       1.       0.       0.     ]
 [ 0.       0.       0.63246  0.63246]
 [ 0.       0.      -0.31623  0.31623]
 [ 0.       0.      -0.31623 -0.31623]
 [ 0.       0.       0.63246 -0.63246]]


If we now take $\varphi_3^{B}$ and $\varphi_4^{B}$ and define
\begin{align}
    \tilde{\varphi}'_1 &= \sqrt{n_1^{\rm imp}} \varphi^{A}_1 + \underbrace{\sqrt{1-n_1^{\rm imp}}}_{=\sqrt{0.83333}} \varphi_1^B
    \\
    \tilde{\varphi}'_2 &= \sqrt{n_2^{\rm imp}} \varphi^{A}_2 + \underbrace{\sqrt{1-n_2^{\rm imp}}}_{=\sqrt{0.16666}} \varphi_4^B
\end{align}
as well as
\begin{align}
    \tilde{\varphi}'_3 &= \varphi^B_2\\
    \tilde{\varphi}'_4 &= \varphi^B_1.
\end{align}

In [13]:
phi_tilde=np.zeros((6,4))

phi_tilde[0:2,0]=n_imp[0]**0.5*phi_imp[0:2,0]
phi_tilde[2:6,0]=(1-n_imp[0])**0.5*phi_env[0:4,0]
phi_tilde[0:2,1]=n_imp[1]**0.5*phi_imp[0:2,1]
phi_tilde[2:6,1]=(1-n_imp[1])**0.5*phi_env[0:4,3]

phi_tilde[2:6,2]=phi_env[:,1]
phi_tilde[2:6,3]=phi_env[:,2]
print(phi_tilde)


[[ 0.28868 -0.6455   0.       0.     ]
 [-0.28868 -0.6455   0.       0.     ]
 [-0.28868 -0.1291   0.63246  0.63246]
 [ 0.57735 -0.2582  -0.31623  0.31623]
 [-0.57735 -0.2582  -0.31623 -0.31623]
 [ 0.28868 -0.1291   0.63246 -0.63246]]


Since we have now four orthogonal vectors we would still need to choose two orthonormal ones to fill up all of the six dimensional space. However, since we only want to construct a Hamiltonian that has the same impurity 1RDM in the ground-state three-particle sector we leave them undefined but instead choose a set of random numbers $\epsilon_1' \leq \epsilon'_2 \leq \epsilon'_3 <  \epsilon'_4 \leq \epsilon'_5 = \epsilon'_6 =0$. For definiteness, let us choose $\epsilon_1' = -4$, $\epsilon'_2= -3 $, $\epsilon'_3=-2$, $\epsilon'_4= -1$.
With these eigenvalues $\epsilon'_i$ and the $\tilde{\varphi}'_i$ we can build a new Hamiltonian   $\boldsymbol{h}^{s}_{\rm new}=\sum_{\mu =1}^{4} \epsilon'_{\mu} \tilde{\varphi}'_{\mu}(i)\tilde{\varphi}'^{*}_{\mu (j)}$:


In [26]:
epsilon_prime=np.zeros(4)
h_new_s=np.zeros((6,6))
for i in range(0,4):
    epsilon_prime[i]=-4+i   

h_new_s=np.zeros((6,6))
h_new_s=multi_dot([phi_tilde,np.diag(epsilon_prime),phi_tilde.transpose()])
    
print(h_new_s)

[[-1.58333 -0.91667  0.08333 -1.16667  0.16667 -0.58333]
 [-0.91667 -1.58333 -0.58333  0.16667 -1.16667  0.08333]
 [ 0.08333 -0.58333 -1.58333  0.76667 -0.16667 -0.11667]
 [-1.16667  0.16667  0.76667 -1.83333  1.03333 -0.16667]
 [ 0.16667 -1.16667 -0.16667  1.03333 -1.83333  0.76667]
 [-0.58333  0.08333 -0.11667 -0.16667  0.76667 -1.58333]]


If we diagonalize the Hamiltonian and take the three lowest eigenvectors (which would be identical to $\tilde{\varphi}'_i$ for i=1,2,3 since we have build this hamiltonian to have these as eigenvectors) we find the three-particle ground-state 1RDM

In [27]:
gamma_s_new=np.dot(phi_tilde[:,0:3],phi_tilde[:,0:3].transpose())
print(gamma_s_new)

[[ 5.00000e-01  3.33333e-01  2.55739e-16  3.33333e-01  7.44393e-17
   1.66667e-01]
 [ 3.33333e-01  5.00000e-01  1.66667e-01  7.35290e-17  3.33333e-01
  -1.45922e-16]
 [ 2.55739e-16  1.66667e-01  5.00000e-01 -3.33333e-01  3.24340e-16
   3.33333e-01]
 [ 3.33333e-01  7.35290e-17 -3.33333e-01  5.00000e-01 -1.66667e-01
   4.75155e-17]
 [ 7.44393e-17  3.33333e-01  3.24340e-16 -1.66667e-01  5.00000e-01
  -3.33333e-01]
 [ 1.66667e-01 -1.45922e-16  3.33333e-01  4.75155e-17 -3.33333e-01
   5.00000e-01]]


and the corresponding ground-state energy is $E'=\epsilon'_1+\epsilon'_2+\epsilon'_3 = -9$. By construction the 1RDM agrees on the impurity but the rest is different. Also, the CAS orbitals that are used in the projection will be different. In our case they become (besides the first two that are always the same)
\begin{align}
    \varphi'^{\rm CAS}_3&=\varphi^{B}_4,
  \label{eq:phi_3_cas_prime}
\\
  \varphi'^{\rm CAS}_4&=\varphi^{B}_1.
  \label{eq:phi_4_cas_prime}
\end{align}
 However, $\varphi^{B}_4$ and $\varphi^{B}_1$ were orbitals that did not belong to the original CAS. That means that also the projection constructed from the hamiltonian $\boldsymbol{h}^s_{\rm new}$ will look very different from the one of $\boldsymbol{h}^{s}$. Thus in this example we have highlighted that by the requirement that the impurity 1RDM is the same there is the possibility to construct completely different projections even in a very simple setting where also the target system is non-interacting and we just consider only a few sites.




# 2. Non-uniqueness of DMET fixed point

Next we are going to show that besides the projection also the fixed point is arbitrary and that it can be arbitrarily far away from the ''exact result''. In our case the ''exact result'' is the three-particle ground state of the following ''target'' Hamiltonian $\boldsymbol{h}_{tar}$:

In [28]:
phi_tar=np.zeros((6,6))
phi_tar_un=np.zeros((6))



phi_tar[2:6,0]=copy.deepcopy(phi_env[:,0])

phi_tar[:,1]=copy.deepcopy(phi[:,0])

phi_tar[:,2]=copy.deepcopy(phi[:,1])

phi_tar[:,3]=copy.deepcopy(phi[:,2])

phi_tar[:,4]=copy.deepcopy(phi[:,3]-np.dot(phi_tar[:,0].transpose(),phi[:,3])*phi_tar[:,0])/ \
copy.deepcopy((np.dot(phi[:,3]-np.dot(phi_tar[:,0].transpose(),phi[:,3])*phi_tar[:,0], \
       phi[:,3]-np.dot(phi_tar[:,0].transpose(),phi[:,3])*phi_tar[:,0]))**0.5)
phi_tar_un[:] = copy.deepcopy(phi[:,4])- np.dot(phi_tar[:,0].transpose(),phi[:,4])*phi_tar[:,0]-\
                np.dot(phi_tar[:,4].transpose(),phi[:,4])*phi_tar[:,4]
phi_tar[:,5]=copy.deepcopy(phi_tar_un[:])/copy.deepcopy(np.dot(phi_tar_un,phi_tar_un))**0.5
    

epsilon_tar   = np.zeros((6))
epsilon_tar[0]= -2
epsilon_tar[1]= -1
epsilon_tar[2]= -0.5
epsilon_tar[3]=  0.5
epsilon_tar[4]=  1
epsilon_tar[5]=  2

h_tar=np.zeros((6,6))
h_tar=multi_dot([phi_tar,np.diag(epsilon_tar),phi_tar.transpose()])

 where we have defined the orthogonal set of eigenfunctions as
 
 \begin{align}
 \{ \phi_1^{\rm tar}=\varphi_1^{B},
     \phi_2^{\rm tar}=\phi_1,
     \phi_3^{\rm tar}=\phi_2,
     \phi_4^{\rm tar}=\phi_{3},
     \phi_5^{\rm tar}=\frac{1}{|\phi_4-\langle \phi_1^{\rm tar}|\phi_4 \rangle \phi_1^{\rm tar}|}(\phi_4-\langle \phi_1^{\rm tar}|\phi_4\rangle \phi_1^{\rm tar}),\nonumber\\
      \phi_6^{\rm tar}=\frac{1}{|\phi_5-\langle \phi_1^{\rm tar}|\phi_5 \rangle \phi_1^{\rm tar}|}(\phi_5-\langle \phi_1^{\rm tar}|\phi_5\rangle \phi_1^{\rm tar})+
      \frac{1}{|\phi_5-\langle \phi_5^{\rm tar}|\phi_5 \rangle \phi_5^{\rm tar}|}(\phi_5-\langle \phi_5^{\rm tar}|\phi_5\rangle \phi_5^{\rm tar}
     )  \}    
 \end{align}
and $\{\phi_1,...,\phi_5 \}$ are the five lowest eigenstates of $\boldsymbol{h_s}$. Further we have chosen
\begin{align*}
    \epsilon_1^{\rm tar}=-2, \epsilon_2^{\rm tar}=-1, \epsilon_3^{\rm tar}=-0.5, \epsilon_4^{\rm tar}=0.5, \epsilon_5^{\rm tar}=1, \epsilon_6^{\rm tar}=2.
\end{align*}
For this Hamiltonian the three particle ground state is $E^{tar}=-3.5$ and the 1RDM is 
$\gamma^{tar}$

In [39]:
gamma_tar=np.dot(phi_tar[:,0:3],phi_tar[:,0:3].transpose())
print(gamma_tar)

[[ 0.49796  0.35483  0.02354 -0.16463 -0.0215   0.3098 ]
 [ 0.35483  0.27354  0.08537 -0.0215   0.0598   0.24796]
 [ 0.02354  0.08537  0.3285   0.1098   0.44796  0.00483]
 [-0.16463 -0.0215   0.1098   0.89796 -0.04517  0.22354]
 [-0.0215   0.0598   0.44796 -0.04517  0.67354 -0.11463]
 [ 0.3098   0.24796  0.00483  0.22354 -0.11463  0.3285 ]]


The impurity 1RDM submatrix reads:

In [24]:
gamma_imp=gamma_tar[0:2,0:2]
print(gamma_imp)

[[0.49796 0.35483]
 [0.35483 0.27354]]


Next we assume that a DMET iteration step led us to an auxiliary Hamiltonian of the form of the Hamiltonian $\boldsymbol{h}^{s}$ and determine the CAS orbitals like we did before we define the embedded Hamiltonian:

$\mathbf{h}^{'\rm tar} =[\mathbf{C}^{\rm CAS}]^T \mathbf{h}^{\rm tar} \mathbf{C}^{\rm CAS}$

In [30]:
h_tar_prime=multi_dot([phi_CAS.transpose(),h,phi_CAS])
print(h_tar_prime)

[[ 0.00000e+00 -1.00000e+00 -6.32456e-01  6.32456e-01]
 [-1.00000e+00  0.00000e+00 -6.32456e-01 -6.32456e-01]
 [-6.32456e-01 -6.32456e-01  6.00000e-01  4.44089e-16]
 [ 6.32456e-01 -6.32456e-01  4.44089e-16 -6.00000e-01]]


Diagonalizing this Hamiltonian and keeping only the two lowest (embedded) orbitals we obtain an embedded 1RDM of the target Hamiltonian in the CAS basis as
\begin{align}
    \boldsymbol{\gamma}'^{\rm tar}_{\rm CAS}&\equiv\sum_{k=1}^2 \varphi_{k}^{\rm emb}(\mu)\varphi_{k}^{\rm emb}(\nu)
\end{align}

In [31]:
n_emb, phi_emb=LA.eigh(h_tar_prime)
gamma_tar_emb = np.dot(phi_emb[:,0:2],phi_emb[:,0:2].transpose()) 
print(np.around(gamma_tar_emb,5))

[[ 0.5      0.33333  0.26352 -0.26352]
 [ 0.33333  0.5      0.26352  0.26352]
 [ 0.26352  0.26352  0.16667 -0.     ]
 [-0.26352  0.26352 -0.       0.83333]]


Transforming the 1RDM into the site basis by
\begin{align}
\gamma'^{\rm tar}_{\rm emb}(i,j)=\sum_{\mu,\nu=1}^4 \gamma'^{\rm tar}_{\rm CAS}(\mu,\nu)
\varphi^{\rm CAS}_{\mu}(i)\varphi^{\rm CAS}_{\nu}(j)
\end{align}
leads to

In [32]:
gamma_tar_ij = multi_dot([phi_CAS,gamma_tar_emb,phi_CAS.transpose()])
print(np.around(gamma_tar_ij,5))

[[ 0.5      0.33333 -0.      -0.16667  0.       0.33333]
 [ 0.33333  0.5      0.33333 -0.      -0.16667 -0.     ]
 [-0.       0.33333  0.4      0.13333 -0.2     -0.26667]
 [-0.16667 -0.       0.13333  0.1     -0.06667 -0.2    ]
 [ 0.      -0.16667 -0.2     -0.06667  0.1      0.13333]
 [ 0.33333 -0.      -0.26667 -0.2      0.13333  0.4    ]]


We notice that the 1RDM $\boldsymbol{\gamma'}^{\rm tar}_{emb}$ constructed from the embedded Hamiltonian does not agree with the target 1RDM $\boldsymbol{\gamma}^{\rm tar}$ even on the impurity $A$. That is, the approximate impurity 1RDM is
\begin{align}
 \boldsymbol{\gamma}'^{\rm tar}_{\rm imp}=\begin{pmatrix}
 0.5 &0.33333 \\
 0.33333 &0.5 
\end{pmatrix},
\end{align}
while it does not agree with the exact impurity 1RDM we have reached self-consistency of the DMET algorithm since
\begin{align}
    \boldsymbol{\gamma}^s_{\rm imp} = \boldsymbol{\gamma}'^{\rm tar}_{\rm imp},
\end{align}
and thus our DMET iteration is finished. Besides that we find completely wrong 1RDMs, also the energy estimate is not necessarily good. To demonstrate this we are going to use the following formula to calculate first the energy of the fragment A:
\begin{align}
\label{eq:tot_energy_new}
\epsilon_{f}^{exact}=\sum_{i=1,2,j=1-6}\boldsymbol{h}^{tar}_{i,j}\gamma^{tar}(j,i)=-0.55242
\end{align}

In [48]:
epsilon_f=0
for ii in range(2):
    for jj in range(6):
        epsilon_f=epsilon_f+h_tar[ii,jj]*gamma_tar[jj,ii]
print(np.around(epsilon_f,5))

-0.55242


However, because in practice we do not have the correct 1RDM that corresponds to this Hamiltonian available we need to calculate the fragment energy using the embedded 1RDM:
\begin{align}
\label{eq:tot_energy_appr}
\epsilon_{f}^{emb}=\sum_{i=1,2,j=1-6}\boldsymbol{h}^{tar}_{i,j}\gamma^{'tar}_{emb}(j,i)=-0.43816
\end{align}


In [50]:
epsilon_f_emb=0
for ii in range(2):
    for jj in range(6):
        epsilon_f_emb=epsilon_f_emb+h_tar[ii,jj]*gamma_tar_ij[jj,ii]
print(np.around(epsilon_f_emb,5))

-0.43816


Following the same procedure after adding to embedded 1RDM the environment orbital that we had originally discarded (so as to have three particles)

\begin{align}
    \gamma_{emb}^{tar,tot}(j,i)= \boldsymbol{\gamma}'^{\rm tar}_{emb}(j,i)+\phi_4^{*B}(j)\phi^B_4(i)
\end{align}

In [51]:
gamma_tot = np.zeros((6,6))
gamma_tot = copy.deepcopy(gamma_tar_ij)
gamma_tot[2:6,2:6] = copy.deepcopy(gamma_tot[2:6,2:6])+ np.dot(phi_env[:,3:4],phi_env[:,3:4].transpose())

we obtain the same wrong fragment energy

In [52]:
epsilon_f_emb_tot=0
for ii in range(2):
    for jj in range(6):
        epsilon_f_emb_tot=epsilon_f_emb_tot+h_tar[ii,jj]*gamma_tot[jj,ii]
print(np.around(epsilon_f_emb_tot,5))

-0.43816
